{% set name = "patricesorter" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/patricesorter-{{ version }}.tar.gz
  sha256: 91836f9eada4752b2ecbb6e683f189661334d491ab200f9f7071e95ff1a1240b

build:
  number: 0
  entry_points:
    - patricesorter = patricesorter.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools-scm
  run:
    - importlib-metadata  # [py<38]
    - pytest
    - pytest-cov
    - python

test:
  imports:
    - docs
    - docs._static
  commands:
    - pip check
    - patricesorter --help
  requires:
    - pip

about:
  home: https://github.com/pyscaffold/pyscaffold/
  summary: Add a short description here!
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - PatriceJada
